= Gravitee.io download page

This repository contains the code of https://download.gravitee.io

It was inspired by https://github.com/qoomon/aws-s3-bucket-browser with some changes:

- replace Vue.js by vanilla Javascript
- remove pagination
- sort the items with natural order

https://rollupjs.org[rollup.js] is used to bundle the page in a single `index.html` file.

== Build the project

WARNING: You will need Node.js 16

Fetch dependencies

[source,bash]
----
❯ yarn install
----

Build the `index.html`

[source,bash]
----
❯ yarn build
----

The `index.html` can be found in `dist/` directory.

== Development

You can start a development server with livereload

[source,bash]
----
❯ yarn start:dev
----

== Publish on S3

WARNING: You will need a Circle CI API Token to be able to publish a new version

To publish the portal you can use the script `.bin/publish.sh`.
- `DRY_RUN=true` will publish to our dry-run bucket: `gravitee-dry-releases-downloads`
- `DRY_RUN=false` will publish to our public bucket: `gravitee-releases-downloads`

[source,bash]
----
CCI_TOKEN=xxxx DRY_RUN=false .bin/publish.sh
----

