version: 2.1

orbs:
  secrethub: secrethub/cli@1.1.0
  aws-s3: circleci/aws-s3@3.0.0

parameters:
  action:
    type: enum
    enum: [ publish, pull_requests ]
    default: pull_requests
  release:
    type: boolean
    default: false
    description: "trigger release flag"
  dry_run:
    type: boolean
    default: true
    description: "Run process in dry run mode ?"

executors:
  node-lts-small:
    docker:
      - image: circleci/node:16.13.1-buster
    resource_class: small
  node-lts-medium:
    docker:
      - image: circleci/node:16.13.1-buster
    resource_class: medium

commands:
  s3-sync:
    description: "Synchronize a local folder with a S3 bucket"
    parameters:
      local_dir:
        type: string
        description: The local folder to sync
      bucket:
        type: string
        description: The S3 bucket
    steps:
      - aws-s3/sync:
          arguments: |
            --endpoint-url https://cellar-c2.services.clever-cloud.com \
            --acl public-read
          from: << parameters.local_dir>>
          to: 's3://<< parameters.bucket >>/'

jobs:
  install:
    executor:
      name: node-lts-small
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn cache
          keys:
            - download-gravitee-v1-yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          name: Save yarn cache
          key: download-gravitee-v1-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - .yarn/cache
          when: always
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  lint-test:
    executor:
      name: node-lts-medium
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run CommitLint
          command: yarn lint:commit
      - run:
          name: Run Prettier
          command: yarn lint
      - run:
          name: Run All Tests
          command: yarn test --coverage
      - store_artifacts:
          path: coverage

  build:
    executor:
      name: node-lts-medium
    parameters:
      dry_run:
        type: boolean
        default: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - when:
          condition:
            equal: [ true, << pipeline.parameters.dry_run >> ]
          steps:
            - run:
                name: Build
                command: yarn build
      - when:
          condition:
            equal: [ false, << pipeline.parameters.dry_run >> ]
          steps:
            - run:
                name: Build
                command: NODE_ENV=production yarn build
      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish-on-s3:
    parameters:
      dry_run:
        type: boolean
        default: true
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - attach_workspace:
          at: .
      - when:
          condition:
            equal: [ true, << pipeline.parameters.dry_run >> ]
          steps:
            - s3-sync:
                local_dir: dist
                bucket: gravitee-dry-releases-downloads
      - when:
          condition:
            equal: [ false, << pipeline.parameters.dry_run >> ]
          steps:
            - s3-sync:
                local_dir: dist
                bucket: gravitee-releases-downloads

workflows:
  version: 2
  branch_validate:
    when:
      and:
        - equal: [ pull_requests, << pipeline.parameters.action >> ]
    jobs:
      - install
      - lint-test:
          requires:
            - install
      - build:
          requires:
            - install

  publish:
    when:
      and:
        - equal: [ publish, << pipeline.parameters.action >> ]
    jobs:
      - install
      - build:
          dry_run: << pipeline.parameters.dry_run >>
          requires:
            - install
      - publish-on-s3:
          context: cicd-orchestrator
          pre-steps:
            - secrethub/env-export:
                secret-path: graviteeio/cicd/graviteebot/infra/zip-bundle-server/clever-cloud-s3/s3cmd/aws_access_key
                var-name: AWS_ACCESS_KEY_ID
            - secrethub/env-export:
                secret-path: graviteeio/cicd/graviteebot/infra/zip-bundle-server/clever-cloud-s3/s3cmd/aws_secret_key
                var-name: AWS_SECRET_ACCESS_KEY
          dry_run: << pipeline.parameters.dry_run >>
          requires:
            - build

